### ISSUE TITLE
QA 이후 배포 전 EditerTextArea 수정사항 반영

### ISSUE THREAD

**Issue by jae-hun-e** [prgrms-fe-devcourse/FEDC5_DevNamu_eunsu#105]
## 🔨 작업 설명

QA에서 에디터 부분 배포전 수정사항을 반영하겠습니다. 
- 비회원 처리 → 로그인 모달로 변경
- 스레드 폰트 따라가겠습니다.

**Comment by Kim-Jaemin420** [comment]
제목에서 어느 파트 수정인지 들어가면 더 좋을 것 같아요~~ㅎㅎ:D

**Comment by jae-hun-e** [comment]
반영했습니다~!
