### ISSUE TITLE
회원가입 로직 구현

### ISSUE THREAD

**Issue by bgyoons** [prgrms-fe-devcourse/FEDC5_DevNamu_eunsu#16]
## 어떤 기능인가요?

회원가입 로직 구현

## 작업 상세 내용

- [ ] 회원가입 axios + react-query 통해 구현
- [ ] 회원가입 시 이미지 첨부 기능 구현 _(드래그&드랍은 V2로 갈 수도 있음)_
- [ ] 회원가입 시 유효성 검사(이메일, 패스워드 유효성 검사)
- [ ] 회원가입 시 중복된 이메일인 경우 에러 처리

**Comment by Kim-Jaemin420** [comment]
흠..살짝 pr 규모가 커질 것 같다는 생각이 들기도 하는데 혹시 로그인과 회원가입을 분리해서 작업하는건 어떠세요?

**Comment by bgyoons** [comment]
> 흠..살짝 pr 규모가 커질 것 같다는 생각이 들기도 하는데 혹시 로그인과 회원가입을 분리해서 작업하는건 어떠세요?

@Kim-Jaemin420 넵! 이 이슈에서는 회원가입만 하고 완료 후에 로그인 새로 이슈 생성해서 하겠습니다!

**Comment by Kim-Jaemin420** [comment]
넵!! 그럼 이슈 제목이랑 내용도 함께 변경 부탁드리겠습니다~~🙏
