### ISSUE TITLE
내가 작성한 글 목록 퍼블리싱

### ISSUE THREAD

**Issue by junly21** [prgrms-fe-devcourse/FEDC5_DevNamu_eunsu#24]
## 어떤 기능인가요?

사이드 바에서 내가 쓴 글 아이콘을 눌렀을 경우 보여지는 페이지입니다.
우선 더미데이터로 UI를 구축한 후, api통신 및 로직은 Feature 이슈에서 구현할 예정입니다.

## 작업 상세 내용

- [ ] 내가 작성한 글 헤더 구현
- [ ] 더미데이터를 통해 내가 작성한 글 리스트 출력
- [ ] 날짜 구분 (더미데이터 활용)

## 참고할만한 자료(선택)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/91151775/15f9eb75-287b-465b-9cde-15f5921fc19d)

**Comment by Kim-Jaemin420** [comment]
올~~~~~사진까지~~~~~
