### ISSUE TITLE
내가 작성한 글 api통신 로직 구현

### ISSUE THREAD

**Issue by junly21** [prgrms-fe-devcourse/FEDC5_DevNamu_eunsu#25]
## 어떤 기능인가요?

기존에 더미데이터를 통해 출력되던 **내가 작성한 글**을 api통신을 통해 데이터를 받아올 수 있도록 합니다.

## 작업 상세 내용

- [ ] GET /posts/author/{authorId} 를 통해 작성한 글을 불러옵니다.
- [ ] response타입인 POST 내부의 날짜를 통해 정렬해줍니다.
- [ ] 내가 작성한 글 클릭 시 navigation을 통해 해당 스레드를 열어줍니다.(v2예정)

## 참고할만한 자료(선택)
![image](https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/91151775/9e40f54f-546a-4e56-b59e-e6d58bbbb729)

![image](https://github.com/prgrms-fe-devcourse/FEDC5_DevNamu_eunsu/assets/91151775/d5692528-ee12-4180-b5b5-ed713a0689f2)

**Comment by Kim-Jaemin420** [comment]
작업 상세 내용에서 (v2 에정) 부분은 이번 pr에서는 작업하지 않는거죠? 확인만 해두려고 질문 드려요 : )

**Comment by junly21** [comment]
여유가 되면 작업하되 우선순위를 미룬다는 의미로 v2로 작성했습니다!
말씀 드리면서 생각해보니 높은 확률로 이번 pr에서는 작업하지 않을 것 같네요...!
